

-- Create Users Table
CREATE TYPE user_role AS ENUM ('Ticket Manager', 'Football Fan');

CREATE TABLE Users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  role user_role NOT NULL,
  phone_number VARCHAR(20)
);


-- Create Matches Table
CREATE TYPE match_status_type AS ENUM ('Available', 'Selling Fast', 'Sold Out', 'Postponed');

CREATE TABLE Matches (
  match_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fixture VARCHAR(150) NOT NULL,
  tournament_category VARCHAR(100) NOT NULL,
  base_ticket_price DECIMAL(10, 2) NOT NULL,
  match_status match_status_type NOT NULL
);
